export const APP_COPY = {
  name: "BookHaven",
  tagline: "A focused shelf of books for builders, readers, and curious teams.",
  homepageTitle: "Curated books for better software and better habits",
  homepageIntro:
    "Browse a compact catalog, add books to your cart, and keep your picks across refreshes.",
  catalogControlsLabel: "Catalog filters",
  catalogPaginationLabel: "Catalog pagination",
  searchLabel: "Search books",
  searchPlaceholder: "Search by title or author",
  searchAction: "Search",
  clearFiltersAction: "Clear filters",
  sortLabel: "Sort books",
  resultsLabel: "results",
  retryAction: "Try again",
  previousPage: "Previous",
  nextPage: "Next",
  ofLabel: "of",
  cartTitle: "Your cart",
  cartIntro: "Review selected books before checkout.",
  cartLink: "View cart",
  cartLabel: "View cart",
  homeLink: "Continue shopping",
  addToCart: "Add to cart",
  addedToCart: "Added",
  addedToCartMessage: "Added to cart",
  decreaseQuantity: "Decrease quantity",
  increasedQuantityMessage: "Increased quantity",
  decreasedQuantityMessage: "Decreased quantity",
  increaseQuantity: "Increase quantity",
  removeItem: "Remove",
  removedFromCartMessage: "Removed from cart",
  clearCart: "Clear cart",
  skuLabel: "SKU",
  authorLabel: "Author",
  quantityLabel: "Quantity",
  priceLabel: "Price",
  totalLabel: "Total",
  itemTotalLabel: "Item total",
  itemSingular: "item",
  itemPlural: "items",
  loadingBooks: "Loading books",
  booksErrorTitle: "Books could not be loaded",
  booksErrorMessage:
    "The database is unavailable. Check the PostgreSQL connection and seeded book records.",
  emptyBooksTitle: "No books available",
  emptyBooksMessage: "The catalog is empty. Seed the database to add books.",
  noMatchingBooksTitle: "No books match your search",
  noMatchingBooksMessage:
    "Try a different title or author, or clear the search field to see every book.",
  emptyCartTitle: "Your cart is empty",
  emptyCartMessage:
    "Your saved cart will appear here. Browse the catalog and add a book when you are ready.",
  adminLoginTitle: "Admin login",
  adminLoginIntro: "Sign in to manage the BookHaven catalog.",
  adminUsernameLabel: "Username",
  adminPasswordLabel: "Password",
  adminLoginAction: "Sign in",
  adminLogoutAction: "Sign out",
  adminShellTitle: "BookHaven Admin",
  adminSignedInAsLabel: "Admin",
  adminDashboardTitle: "Catalog",
  adminDashboardIntro: "Manage books, prices, and cover URLs.",
  adminCreateAction: "Create book",
  adminEditAction: "Edit",
  adminDeleteAction: "Delete",
  adminSaveAction: "Save book",
  adminCancelAction: "Cancel",
  adminCreateTitle: "Create book",
  adminDetailTitle: "Book detail",
  adminBookListTitle: "Book records",
  adminActionsLabel: "Actions",
  adminShowingLabel: "Showing",
  adminTotalBooksLabel: "Total books",
  adminCurrentPageLabel: "Current page",
  adminServerSearchLabel: "Server search",
  adminRequiredFieldsTitle: "Required fields",
  adminOptionalFieldsTitle: "Optional fields are auto-generated if blank",
  adminDefaultCoverPreview: "Default cover preview",
  adminSkuLabel: "SKU",
  adminTitleLabel: "Title",
  adminDescriptionLabel: "Description",
  adminCoverImageUrlLabel: "Cover image URL",
  adminTitlePlaceholder: "Book title",
  adminSearchPlaceholder: "Search by title, author, or SKU",
  adminPricePlaceholder: "Price in cents",
  adminAuthorPlaceholder: "Generated if blank",
  adminSkuPlaceholder: "Generated if blank",
  adminDescriptionPlaceholder: "Generated if blank",
  adminCoverImageUrlPlaceholder: "Default cover if blank",
  adminLoadingBooks: "Loading admin data",
  adminEmptyBooksTitle: "No books yet",
  adminEmptyBooksMessage: "Create the first admin-managed book.",
  adminLoginSuccess: "Signed in",
  adminLogoutSuccess: "Signed out",
  adminSaveSuccess: "Book saved",
  adminDeleteSuccess: "Book deleted",
  adminLogoutFailure: "Could not sign out. Try again.",
  adminSaveFailure: "Book could not be saved. Try again.",
  adminDeleteFailure: "Book could not be deleted. Try again.",
  adminUnauthorizedMessage: "Admin access is required.",
  adminInvalidLoginMessage: "Username or password is invalid.",
  adminInvalidPayloadMessage: "Enter valid book details.",
  adminDuplicateSkuMessage: "A book with this SKU already exists.",
  adminNotFoundMessage: "Book not found.",
  adminGenericErrorMessage: "Admin request failed. Try again.",
  adminConfirmCancelAction: "Cancel",
  adminConfirmSaveTitle: "Save book changes",
  adminConfirmSaveMessage: "Confirm before saving this book.",
  adminConfirmSaveAction: "Save book",
  adminConfirmDeleteTitle: "Delete book",
  adminDeleteConfirmMessage: "Delete this book? This cannot be undone.",
  adminConfirmDeleteAction: "Delete book",
  adminConfirmLogoutTitle: "Sign out",
  adminConfirmLogoutMessage: "Confirm before ending this admin session.",
  adminConfirmLogoutAction: "Sign out"
} as const;
