export const APP_COPY = {
  name: "BookHaven",
  tagline: "A focused shelf of books for builders, readers, and curious teams.",
  homepageTitle: "Curated books for better software and better habits",
  homepageIntro:
    "Browse a compact catalog, add books to your cart, and keep your picks across refreshes.",
  catalogControlsLabel: "Catalog filters",
  catalogPaginationLabel: "Catalog pagination",
  searchLabel: "Search books",
  searchPlaceholder: "Search by title or author",
  searchAction: "Search",
  clearFiltersAction: "Clear filters",
  sortLabel: "Sort books",
  resultsLabel: "results",
  retryAction: "Try again",
  previousPage: "Previous",
  nextPage: "Next",
  pageStatus: "Page",
  ofLabel: "of",
  cartTitle: "Your cart",
  cartIntro: "Review selected books before checkout.",
  cartLink: "View cart",
  cartLabel: "View cart",
  homeLink: "Continue shopping",
  addToCart: "Add to cart",
  addedToCart: "Added",
  addedToCartMessage: "Added to cart",
  decreaseQuantity: "Decrease quantity",
  increasedQuantityMessage: "Increased quantity",
  decreasedQuantityMessage: "Decreased quantity",
  increaseQuantity: "Increase quantity",
  removeItem: "Remove",
  removedFromCartMessage: "Removed from cart",
  clearCart: "Clear cart",
  skuLabel: "SKU",
  authorLabel: "Author",
  quantityLabel: "Quantity",
  priceLabel: "Price",
  totalLabel: "Total",
  itemTotalLabel: "Item total",
  itemSingular: "item",
  itemPlural: "items",
  loadingBooks: "Loading books",
  booksErrorTitle: "Books could not be loaded",
  booksErrorMessage:
    "The database is unavailable. Check the PostgreSQL connection and seeded book records.",
  emptyBooksTitle: "No books available",
  emptyBooksMessage: "The catalog is empty. Seed the database to add books.",
  noMatchingBooksTitle: "No books match your search",
  noMatchingBooksMessage:
    "Try a different title or author, or clear the search field to see every book.",
  emptyCartTitle: "Your cart is empty",
  emptyCartMessage:
    "Your saved cart will appear here. Browse the catalog and add a book when you are ready.",
  cartRestored: "Cart restored from this browser",
  cartUpdated: "Cart updated"
} as const;
